<?php

namespace App\Actions\Inventory;

use App\Models\Inventory\StockBalance;
use App\Models\Inventory\StockMovement;
use App\Models\Inventory\StockMovementItem;
use App\Models\Inventory\StockMovementType;
use App\Models\Purchasing\SupplierVoucher;
use Illuminate\Validation\ValidationException;

class ReverseStockMovementForVoucher
{
    /**
     * Reverses the stock movement generated by a supplier voucher.
     *
     * @throws ValidationException
     */
    public function handle(SupplierVoucher $voucher, int $userId, ?string $reason = null): ?StockMovement
    {
        /** @var StockMovement|null $originalMovement */
        $originalMovement = StockMovement::query()
            ->where('supplier_voucher_id', $voucher->id)
            ->lockForUpdate()
            ->first();

        if ($originalMovement === null) {
            return null;
        }

        // Idempotencia: si ya existe reversión, devolverla
        $existingReversal = StockMovement::query()
            ->where('reversal_of_movement_id', $originalMovement->id)
            ->first();

        if ($existingReversal !== null) {
            return $existingReversal;
        }

        /** @var StockMovementType $reversalType */
        $reversalType = StockMovementType::query()
            ->where('code', StockMovementType::CODE_PURCHASE_ENTRY_REVERSAL)
            ->where('is_active', true)
            ->firstOrFail();

        $originalItems = $originalMovement->items()
            ->with('article')
            ->lockForUpdate()
            ->get();

        // Validar primero que todos los saldos resultantes no queden negativos
        foreach ($originalItems as $item) {
            $delta = -1 * (float) $item->quantity;

            /** @var StockBalance|null $balance */
            $balance = StockBalance::query()
                ->where('article_id', $item->article_id)
                ->where('warehouse_id', $originalMovement->warehouse_id)
                ->lockForUpdate()
                ->first();

            $currentQuantity = $balance !== null ? (float) $balance->quantity : 0.0;
            $newQuantity = round($currentQuantity + $delta, 3);

            if ($newQuantity < 0) {
                $articleDesc = $item->article->description;
                throw ValidationException::withMessages([
                    'stock' => "No se puede anular el comprobante: el stock disponible del artículo '{$articleDesc}' no es suficiente para revertir el ingreso.",
                ]);
            }
        }

        $formattedNumber = "{$voucher->letter->value} {$voucher->point_of_sale}-{$voucher->number}";
        $notes = "Reversión de entrada por anulación de remito {$formattedNumber}".($reason ? ": {$reason}" : '');

        $reversalMovement = StockMovement::create([
            'stock_movement_type_id' => $reversalType->id,
            'warehouse_id' => $originalMovement->warehouse_id,
            'supplier_voucher_id' => null,
            'reversal_of_movement_id' => $originalMovement->id,
            'notes' => $notes,
            'user_id' => $userId,
            'created_at' => now(),
        ]);

        foreach ($originalItems as $item) {
            $delta = -1 * (float) $item->quantity;

            /** @var StockBalance $balance */
            $balance = StockBalance::query()
                ->where('article_id', $item->article_id)
                ->where('warehouse_id', $originalMovement->warehouse_id)
                ->lockForUpdate()
                ->firstOrFail();

            $newQuantity = round((float) $balance->quantity + $delta, 3);

            StockMovementItem::create([
                'stock_movement_id' => $reversalMovement->id,
                'article_id' => $item->article_id,
                'quantity' => sprintf('%.3f', $delta),
                'system_quantity' => null,
            ]);

            StockBalance::updateOrCreate(
                [
                    'article_id' => $item->article_id,
                    'warehouse_id' => $originalMovement->warehouse_id,
                ],
                [
                    'quantity' => sprintf('%.3f', $newQuantity),
                ]
            );
        }

        return $reversalMovement;
    }
}
